name: sentra_trade
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  image_picker: ^1.2.1
  fl_chart: ^1.2.0
  share_plus: ^10.1.0
  csv: ^6.0.0
  shared_preferences: ^2.5.5
  local_auth: ^3.0.1
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  build_runner: 2.4.9
  isar_generator: ^3.1.0+1

flutter:

  uses-material-design: true
